aiskillconfig:
  '@uniquename': ais_FormFillFieldOptOut_practmp_stockreceiving_practmp_receivingnumber
  aiskill: FormFillFieldOptOut
  attribute:
    entityid.logicalname: practmp_stockreceiving
    logicalname: practmp_receivingnumber
  description: practmp_StockReceiving - Receiving Number Form fill opt out
  entity:
    logicalname: practmp_stockreceiving
  iscustomizable: 1
  scope: 1
  statecode: 0
  statuscode: 1
